// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMomi63YIpYqE13lbRMvMGzwb3_BPP9Oo',
    appId: '1:572765154031:web:4e4867f3abbb2d2c8d491a',
    messagingSenderId: '572765154031',
    projectId: 'peacock-f7fa5',
    authDomain: 'peacock-f7fa5.firebaseapp.com',
    storageBucket: 'peacock-f7fa5.appspot.com',
    measurementId: 'G-7Z3ZCZ0DL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwgOcjLUCyiY2RtcLvYkq5MYpNDVYSq3U',
    appId: '1:572765154031:android:0559103bc0b285f78d491a',
    messagingSenderId: '572765154031',
    projectId: 'peacock-f7fa5',
    storageBucket: 'peacock-f7fa5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB7jlgcuVAQfH9AC_zukfEA1nZtdMzRJI',
    appId: '1:572765154031:ios:2fe8d07ad18608ee8d491a',
    messagingSenderId: '572765154031',
    projectId: 'peacock-f7fa5',
    storageBucket: 'peacock-f7fa5.appspot.com',
    iosBundleId: 'com.pecock.pecockapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB7jlgcuVAQfH9AC_zukfEA1nZtdMzRJI',
    appId: '1:572765154031:ios:2fe8d07ad18608ee8d491a',
    messagingSenderId: '572765154031',
    projectId: 'peacock-f7fa5',
    storageBucket: 'peacock-f7fa5.appspot.com',
    iosBundleId: 'com.pecock.pecockapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMomi63YIpYqE13lbRMvMGzwb3_BPP9Oo',
    appId: '1:572765154031:web:a986799e00698a788d491a',
    messagingSenderId: '572765154031',
    projectId: 'peacock-f7fa5',
    authDomain: 'peacock-f7fa5.firebaseapp.com',
    storageBucket: 'peacock-f7fa5.appspot.com',
    measurementId: 'G-S8QHTX0R8Q',
  );
}
